# Generated by Django 3.0.11 on 2021-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='图片名称(查询时可用)')),
                ('file', models.FileField(upload_to='upload', verbose_name='请选择上传的图片')),
                ('content', models.CharField(max_length=200, verbose_name='解析后的字母')),
            ],
        ),
    ]
